---
- hosts: AWS
  vars:
    http_port: 80
  become: true
  become_user: ubuntu
  become_method: sudo

  tasks:
  - name: ensure apache is at the latest version
    apt:
      name: httpd
      state: latest
  - copy:
      content: |
               <BR> <h2> Hello World V1 made by Ansible through Terraform. <BR></h2>
      dest: /var/www/html/index.html
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
